language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25

    - extra-android-m2repository

env:
  - ANDROID_HOME=$HOME/android-sdk

script:
   - ./gradlew build connectedCheck

