version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha

    resource_class: large

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Project Dependencies and Caching
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: pre-dependencies
          command: sudo pip install codecov

      - run:
          name: Build and execute unit tests
          command: ./gradlew build test jacocoTestReport --stacktrace

      - run:
          name: post-test
          command: codecov