version: 2

general:
  branches:
    only:
      - master
      - development

jobs:
  build:
    working_directory: ~/convalida

    docker:
      - image: circleci/android:api-28-alpha

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      
      - run:
         name: Chmod permissions
         command: sudo chmod +x ./gradlew

      - run:
          name: Install Codecov
          command: sudo pip install codecov

      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies

      - run:
          name: Run unit tests
          command: ./gradlew test jacocoTestReport --stacktrace

      - run:
          name: Send test reports to Codecov
          command: codecov
