version: 2
jobs:
  build:

    working_directory: ~/convalida

    docker:
      - image: circleci/android:api-27-alpha

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - run:
          name: Install Codecov
          command: sudo pip install codecov

      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies

      - run:
          name: Run unit tests
          command: ./gradlew test jacocoTestReport --stacktrace

      - run:
          name: Send test reports to Codecov
          command: codecov

  instrumented_tests:

    working_directory: ~/convalida

    docker:
        - image: bitriseio/docker-android:v2017_09_09-06_45-b744

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - run:
          name: Lists installed targets
          command: android list target
          environment:
            TERM: dumb

      - run:
          name: List available targets and other sdk modules
          command: sdkmanager --list --include_obsolete --verbose
          environment:
            TERM: dumb

      - run:
          name: Create avd
          command: echo no | avdmanager create avd -n testEmulator -k "system-images;android-24;default;armeabi-v7a"
          environment:
            TERM: dumb

      - run:
          name: Start emulator
          command: /opt/android-sdk-linux/emulator/emulator -avd testEmulator -no-audio -no-window
          background: true
          environment:
            TERM: dumb

      - run:
          name: Wait for emulator
          command: ./android-wait-for-boot.sh
          environment:
            TERM: dumb

      - run:
          name: Remove lock screen
          command: adb shell input keyevent 82
          environment:
            TERM: dumb

      - run:
          name: Instrumentation testing
          command: ./gradlew connectedCheck
          environment:
            TERM: dumb

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - instrumented_tests:
          requires:
            - build