version: 2.0

general:
  branches:
    only:
      - master
      - develop

defaults: &defaults
  working_directory: ~/convalida

  docker:
    - image: circleci/android:api-29

  environment:
    JVM_OPTS: -Xmx1024m

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew ./checksum.sh

      - run:
          name: Generate cache key
          command: ./checksum.sh /tmp/checksum.txt

      - restore_cache:
          key: gradle-{{ checksum "/tmp/checksum.txt" }}

      - run:
          name: Download Dependencies
          command: ./gradlew dependencies

      - run:
          name: Assemble project
          command: ./gradlew clean assemble lint

      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: gradle-{{ checksum "/tmp/checksum.txt" }}

      - persist_to_workspace:
          root: .
          paths:
            - build
            - convalida-annotations/build
            - convalida-compiler/build
            - convalida-databinding/build
            - convalida-ktx/build
            - convalida-runtime/build
            - convalida-validators/build
            - sample/build

  test:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew ./checksum.sh

      - run:
          name: Generate cache key
          command: ./checksum.sh /tmp/checksum.txt

      - restore_cache:
          key: gradle-{{ checksum "/tmp/checksum.txt" }}

      - run:
          name: Install Codecov
          command: sudo pip install codecov

      - run:
          name: Run unit tests
          command: ./gradlew test jacocoTestReport --stacktrace

      - run:
          name: Send test reports to Codecov
          command: codecov

  deploy_snapshot:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew ./checksum.sh

      - run:
          name: Generate cache key
          command: ./checksum.sh /tmp/checksum.txt

      - restore_cache:
          key: gradle-{{ checksum "/tmp/checksum.txt" }}

      - run:
          name: Deploy Snapshot to Maven
          command: ./gradlew uploadArchives -P$SONATYPE_NEXUS_USERNAME -P$SONATYPE_NEXUS_PASSWORD

workflows:
  version: 2
  build_test_deploy_snapshot:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy_snapshot:
          requires:
            - test
          filters:
            branches:
              only: develop